### ISSUE TITLE
Update Training steps to include appropriate dataset 

### ISSUE THREAD

**Issue by MichaelClifford** [redhat-et/ilab-on-ocp#49]
While developing the pipeline we used the same dataset for both phases of training. For a proper instructLab run, we need to use a "knowledge dataset" for phase 1 training and a "skills dataset" for phase 2 training. We should be able to get one of each type of dataset from the SDG process. 

Currently the input data for training is defined here:
https://github.com/redhat-et/ilab-on-ocp/blob/8748546911c5188ca392a4166d7a2a5231b2b4e3/training/run_main_ds.py#L32 

and it looks like `--data_output_dir /input_data/processed_data` is being used to define where the input training data is found in the KFP component for our pyTorchJob. 

https://github.com/redhat-et/ilab-on-ocp/blob/8748546911c5188ca392a4166d7a2a5231b2b4e3/training/components.py#L113

We should make sure this behavior is dynamic based on the `phase_name` parameter to use the correct data set for each phase.

**Comment by leseb** [comment]
Fixed in https://github.com/redhat-et/ilab-on-ocp/pull/113?

**Comment by MichaelClifford** [comment]
closed by #113
