### ISSUE TITLE
Expose Node and GPU parameters to the pipeline users 

### ISSUE THREAD

**Issue by MichaelClifford** [redhat-et/ilab-on-ocp#52]
Currently the two parameters for number of nodes, `nnodes`, and number of GPU's per node `nprocPerNode` are hard coded in out training component. 

https://github.com/redhat-et/ilab-on-ocp/blob/8748546911c5188ca392a4166d7a2a5231b2b4e3/training/components.py#L88-L89

We should change this so that they are pipeline arguments (with the current hard coded values as defaults). This will allow the a user to customize these values via the "Create run" Dashboard.

**Comment by leseb** [comment]
https://github.com/redhat-et/ilab-on-ocp/pull/61
